version: '3.8'

services:
    postgres:
        image: ankane/pgvector
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: testuser
            POSTGRES_PASSWORD: testpassword
            POSTGRES_DB: ttpdf-db
        ports:
            - '1234:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
